#+TITLE: Shapeless Blog

Shapeless-blog is a minimalistic blogging tool written in Go.

It uses a RESTful api for CRUD actions, provides basic token based
authentication.

All blog posts are server rendered which no JavaScript is involved.

Using a homemade data structure instead of SQL was a BIG mistake.

* Dependencies
- Go
- sqlite3

* Installation
Make sure you have ~go~ and ~sqlite~ installed in your machine.
#+begin_src shell
  git clone https://github.com/drshapeless/shapeless-blog.git
  cd shapeless-blog
  make
  sudo make install
#+end_src

* Usage
Show options.
#+begin_src shell
  shapeless-blog -h
#+end_src

There are only three options.
#+begin_example
  Usage of ./bin/shapeless-blog:
    -dir string
        shapeless-blog directory (default "/home/jacky/shapeless-blog")
    -migrate
        Migrate shapeless-blog database
    -port int
        shapeless-blog port (default 9398)
#+end_example

Run shapeless-blog.
#+begin_src shell
  shapeless-blog
#+end_src

By default, slblog runs on port 9398. (I smashed my face into keyboard
to get this magical number.)

* Nginx
We can use Nginx to reverse proxy to this application. Here is an example.
#+begin_src nginx
  server {
    server_name blog.drshapeless.com;

    location / {
      proxy_pass http://127.0.0.1:9398/;
    }
  }
#+end_src

* Run as daemon
slblog relies on the init system to run as daemon. But since I use
OpenRC instead of systemd, only OpenRC sample script is
provided. [[./init/shapeless-blog.init][sample init script]]

Remember to change the basedir before using.

Install the init script.
#+begin_src shell
  cp shapeless-blog.init /etc/init.d/shapeless-blog
  chmod +x /etc/init.d/shapeless-blog
#+end_src

In OpenRC.
#+begin_src shell
  rc-update add shapeless-blog default

  rc-service shapeless-blog start
  rc-service shapeless-blog stop
#+end_src

* TODO Blogging
The documentation is not yet finished.
